language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1

before_script:
  - composer install --dev

script:
  - vendor/phpunit/phpunit/phpunit --colors=always --bootstrap ./tests/bootstrap.php  ./tests --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v

